#!/usr/bin/env bash
#
# Inventory the tests CI cannot run, so that "skipped" is never silent.
#
# Several tests in this package are guarded by an opt-in environment variable
# because they need a Metal GPU, the ~21.6 GB reference checkpoint, or both.
# CI leaves those variables unset, which means CI reports green while never
# executing them. That is fine -- GitHub-hosted runners have neither the
# checkpoint nor a real GPU -- but it is only honest if the set of tests in
# that state is written down and kept current.
#
# This script prints that set, derived from the sources. `--check` compares it
# against the inventory block committed in docs/ci-coverage.md and fails on
# drift, so a NEW box-only test cannot appear without the coverage doc naming
# it.
#
# `--check` also verifies the GATES list itself. Comparing generated output to
# the doc catches a new gated FILE, but it is blind to a new gate VARIABLE: a
# test gated on some novel MLXFAST_RUN_* that GATES does not list generates no
# rows, matches the doc exactly, and skips in silence -- precisely the failure
# this script exists to prevent. So the gate names are re-derived from Tests/
# and any name GATES does not know about fails the run.
#
# Usage:  tools/ci-box-only-inventory.sh [--check]
# Exit:   0 in sync (or, without --check, always after printing)
#         1 drift between the sources and docs/ci-coverage.md, or a gate
#           variable used in Tests/ that GATES does not list

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
doc="${repo_root}/docs/ci-coverage.md"
begin_marker='<!-- BEGIN box-only-inventory (generated by tools/ci-box-only-inventory.sh) -->'
end_marker='<!-- END box-only-inventory -->'

# Every opt-in gate that keeps a test off CI hardware. Adding a new gate
# variable to the test suite without adding it here would reopen the silent
# skip, so this list is part of the contract.
GATES=(
  MLXFAST_RUN_GEMMA4_UPSTREAM_EQUIVALENCE
  MLXFAST_RUN_MLX_RUNTIME_TESTS
  MLXFAST_RUN_QWEN_REFERENCE_PARITY
)

# Re-derive the gate names from Tests/ and fail on any GATES does not list.
# Keyed on the MLXFAST_RUN_ prefix, which is the naming convention every opt-in
# gate in this suite follows; a checkpoint-path variable such as
# MLXFAST_LAGUNA_EQUIVALENCE_WEIGHTS_PATH selects material for a gated test
# rather than gating one, and is correctly not matched.
check_gates_are_complete() {
  local found gate known unlisted=()

  while IFS= read -r found; do
    known=0
    for gate in "${GATES[@]}"; do
      if [[ "${found}" == "${gate}" ]]; then
        known=1
        break
      fi
    done
    if [[ ${known} -eq 0 ]]; then
      unlisted+=("${found}")
    fi
  done < <(
    cd "${repo_root}" &&
      grep -rhoE 'MLXFAST_RUN_[A-Z0-9_]+' Tests 2>/dev/null | LC_ALL=C sort -u
  )

  if [[ ${#unlisted[@]} -eq 0 ]]; then
    return 0
  fi

  echo "FAIL  gate variable used in Tests/ but not listed in this script's GATES array:" >&2
  printf '        %s\n' "${unlisted[@]}" >&2
  cat >&2 <<'EOF'

A test gated on a variable this inventory does not know about produces no rows,
so the drift check above it passes while the test never runs anywhere CI can
see. Add the variable to GATES in tools/ci-box-only-inventory.sh, regenerate,
and say in docs/ci-coverage.md where its tests DO run.
EOF
  return 1
}

generate() {
  # Count GATE EXPRESSIONS -- `environment["<gate>"]`, the form every guard and
  # hoisted gate constant in Tests/ uses -- not bare mentions of the variable
  # name. A comment naming the variable is not a gate: before 2026-08-27 the
  # count was `grep -c` on the bare name, and TargetQuantizationBindTests sat
  # in this inventory on the strength of one comment while all eight of its
  # tests ran ungated (the 2026-08-26 CI incident). Bare-name mentions still
  # matter for gate DISCOVERY, so check_gates_are_complete keeps the loose
  # match; only the per-file accounting is strict.
  local gate file count needle
  for gate in "${GATES[@]}"; do
    needle="environment[\"${gate}\"]"
    while IFS= read -r file; do
      count="$(grep -cF "${needle}" "${repo_root}/${file}")"
      printf '%s %s %s\n' "${gate}" "${file}" "${count}"
    done < <(
      cd "${repo_root}" &&
        grep -rlF "${needle}" Tests 2>/dev/null | LC_ALL=C sort
    )
  done
}

committed() {
  if [[ ! -f "${doc}" ]]; then
    echo "ci-box-only-inventory: missing ${doc}" >&2
    exit 1
  fi
  awk -v b="${begin_marker}" -v e="${end_marker}" '
    $0 == b { inside = 1; next }
    $0 == e { inside = 0; next }
    inside && $0 !~ /^```/ && NF { print }
  ' "${doc}"
}

if [[ "${1:-}" != "--check" ]]; then
  generate
  exit 0
fi

# Before the doc comparison: an unlisted gate variable would make that
# comparison agree about a set that is missing rows.
check_gates_are_complete

if diff -u <(committed) <(generate) >/dev/null 2>&1; then
  echo "ci-box-only-inventory: docs/ci-coverage.md matches the sources ($(generate | wc -l | tr -d ' ') gated files, ${#GATES[@]} gate variables)"
  exit 0
fi

echo "FAIL  box-only inventory drift: docs/ci-coverage.md does not match the test sources" >&2
echo "      (-- committed in docs/ci-coverage.md, ++ derived from Tests/)" >&2
diff -u <(committed) <(generate) >&2 || true
cat >&2 <<'EOF'

A test gated behind one of the opt-in environment variables does not run on CI
hardware. Regenerate the inventory and say in docs/ci-coverage.md where the new
one DOES run:

    tools/ci-box-only-inventory.sh
EOF
exit 1
